"""自部署用的完整 Supabase schema：建齐全部云端表、唯一约束与 RLS。

上游只版本化了少数表（factor_ic / review_* / shadow_ledger 的完整 DDL，以及
recommendation_tracking / signal_policy_shadow_runs / daily_nav 的补列），其余表
只存在于作者的生产库里。这里按写入与读取代码反推字段，给新建的 Supabase 项目
一次性建库用。与 core/*_schema.py 同一套做法：不提交 .sql，由
``scripts/print_self_host_ddl.py`` 打印后在 SQL Editor 执行。

约定：
- 已有模块版本化的列/表直接引用，不在这里重抄，上游改 schema 时自动跟上。
- 日期列一律 ``date``（写入侧都是 YYYY-MM-DD）；``recommend_date`` 是 YYYYMMDD 整数。
- 结构化或列表字段用 ``jsonb``——写入侧传 dict / list，读取侧按 JSON 解析。
- 每个 upsert 的 on_conflict 键都必须有同列的唯一约束，否则 PostgREST 报 42P10。
- 共享表只开放 authenticated 读；写入走 service_role（绕过 RLS），与
  ``WYCKOFF_WRITE_CONTEXT=server_job`` 的写库边界一致。
"""

from __future__ import annotations

from dataclasses import dataclass

from core import (
    daily_nav_schema,
    factor_ic_schema,
    recommendation_tracking_schema,
    review_capture_schema,
    review_shadow_lane_schema,
    shadow_ledger_schema,
    signal_policy_shadow_schema,
)
from core.candidate_metadata import CANDIDATE_ATTRIBUTION_COLUMNS
from core.constants import (
    TABLE_CONCEPT_HEAT_HISTORY,
    TABLE_DAILY_NAV,
    TABLE_EXTERNAL_SEED_OBSERVATIONS,
    TABLE_FACTOR_IC_DAILY,
    TABLE_MARKET_SIGNAL_DAILY,
    TABLE_PORTFOLIO_POSITIONS,
    TABLE_PORTFOLIOS,
    TABLE_RECOMMENDATION_TRACKING,
    TABLE_RECOMMENDATION_TRACKING_HK,
    TABLE_RECOMMENDATION_TRACKING_US,
    TABLE_REVIEW_CAPTURE_DAILY,
    TABLE_REVIEW_SHADOW_LANE_DAILY,
    TABLE_SIGNAL_HEALTH_DAILY,
    TABLE_SIGNAL_OBSERVATIONS,
    TABLE_SIGNAL_OUTCOMES,
    TABLE_SIGNAL_PENDING,
    TABLE_SIGNAL_POLICY_SHADOW_RUNS,
    TABLE_SIGNAL_REGISTRY,
    TABLE_STRATEGY_ATTRIBUTION_REPORTS,
    TABLE_STRATEGY_POLICY_CANDIDATES,
    TABLE_STRATEGY_REFLECTIONS,
    TABLE_THEME_RADAR_SNAPSHOT,
    TABLE_TRADE_ORDERS,
    TABLE_USER_SETTINGS,
)

# 只在 Web 端使用、core/constants.py 没有登记的表。
TABLE_PLANET_MEMBERS = "planet_members"
TABLE_USER_ACTIVITY_EVENTS = "user_activity_events"
TABLE_USER_DAILY_ACTIVITY = "user_daily_activity"
TABLE_ANALYTICS_EXCLUDED_USERS = "analytics_excluded_users"

# 访问模式 → RLS 策略，见 _policy_statements。
OWN_USER_READ = "own_user_read"  # 只读自己的行（user_id = auth.uid()）
OWN_USER_ALL = "own_user_all"  # 自己的行可读写
ACTIVITY_EVENTS = "activity_events"  # 自己的行可插入、可读
ACTIVITY_DAILY = "activity_daily"  # 自己的行可读、插入、更新
PORTFOLIO_ALL = "portfolio_all"  # portfolio_id = USER_LIVE:<uid> 的行可读写
PORTFOLIO_READ = "portfolio_read"  # 同上但只读，写入由服务端任务完成
SHARED_READ = "shared_read"  # 所有登录用户可读
SERVICE_ONLY = "service_only"  # 只允许 service_role

Column = tuple[str, str]

_ID: Column = ("id", "bigint generated by default as identity primary key")
_CREATED_AT: Column = ("created_at", "timestamptz not null default now()")
_UPDATED_AT: Column = ("updated_at", "timestamptz not null default now()")


@dataclass(frozen=True)
class TableSpec:
    name: str
    columns: tuple[Column, ...]
    access: str
    constraints: tuple[str, ...] = ()
    indexes: tuple[str, ...] = ()
    comment: str = ""


def _versioned(columns: tuple[tuple[str, str, str], ...]) -> tuple[Column, ...]:
    """把 core/*_schema.py 里 (列名, 类型, 注释) 的补列常量转成本模块的列。"""
    return tuple((name, spec) for name, spec, _note in columns)


def _candidate_attribution_columns() -> tuple[Column, ...]:
    jsonb_columns = {"candidate_reasons", "candidate_metrics", "dynamic_shadow_promotion"}
    numeric_columns = {
        "mainline_score",
        "theme_score",
        "stock_role_score",
        "quality_score",
        "timing_score",
        "dynamic_shadow_score",
    }

    def spec(name: str) -> str:
        if name in jsonb_columns:
            return "jsonb"
        return "numeric" if name in numeric_columns else "text"

    return tuple((name, spec(name)) for name in CANDIDATE_ATTRIBUTION_COLUMNS)


# recommendation_performance.build_market_performance_updates 回写的绩效列，三个市场共用。
_PERFORMANCE_COLUMNS: tuple[Column, ...] = (
    ("mfe_pct", "numeric"),
    ("mae_pct", "numeric"),
    ("range_amp_pct", "numeric"),
    ("mfe_price", "numeric"),
    ("mae_price", "numeric"),
    ("mfe_date", "integer"),
    ("mae_date", "integer"),
    ("stop_loss_sim_pct", "numeric"),
    ("performance_days", "integer"),
    ("performance_updated_at", "timestamptz"),
)

_TRACKING_BASE_COLUMNS: tuple[Column, ...] = (
    ("name", "text not null default ''"),
    ("recommend_reason", "text not null default ''"),
    ("recommend_date", "integer not null"),
    ("initial_price", "numeric not null default 0"),
    ("current_price", "numeric not null default 0"),
    ("change_pct", "numeric not null default 0"),
    ("funnel_score", "numeric"),
    ("is_ai_recommended", "boolean not null default false"),
)

# core.recommendation_payload._extract_recommendation_attribution 的输出列（去掉候选元数据，另行拼接）。
_RECOMMENDATION_ATTRIBUTION_COLUMNS: tuple[Column, ...] = (
    ("primary_signal", "text"),
    ("signal_types", "jsonb"),
    ("signal_track", "text"),
    ("market_regime", "text"),
    ("selection_source", "text"),
    ("selection_rank", "integer"),
    ("selection_is_fill", "boolean not null default false"),
    ("priority_score", "numeric"),
    ("trigger_score", "numeric"),
    ("stage", "text"),
    ("industry", "text"),
    ("sector_state_code", "text"),
    ("sector_state", "text"),
    ("sector_note", "text"),
    ("sector_guidance", "text"),
    ("exit_signal", "text"),
    ("exit_price", "numeric"),
    ("exit_reason", "text"),
    ("strategic_theme", "text"),
    ("strategic_theme_score", "numeric"),
    ("strategic_stock_score", "numeric"),
    ("strategic_theme_state", "text"),
    ("strategic_theme_bonus", "numeric"),
    ("springboard_a", "boolean not null default false"),
    ("springboard_b", "boolean not null default false"),
    ("springboard_c", "boolean not null default false"),
    ("springboard_combo", "text"),
    ("springboard_grade", "text"),
    ("springboard_met_count", "integer not null default 0"),
    ("springboard_support", "numeric"),
    ("springboard_touch_count", "integer not null default 0"),
    ("springboard_evidence", "jsonb"),
    ("springboard_scored", "boolean not null default false"),
)


def _dedupe(columns: tuple[Column, ...]) -> tuple[Column, ...]:
    """按列名去重，保留首次出现的定义（补列常量可能与反推的列重叠）。"""
    seen: set[str] = set()
    out = []
    for name, spec in columns:
        if name not in seen:
            seen.add(name)
            out.append((name, spec))
    return tuple(out)


def _tracking_table(name: str, code_type: str, extra: tuple[Column, ...] = ()) -> TableSpec:
    return TableSpec(
        name=name,
        columns=_dedupe(
            (_ID, ("code", f"{code_type} not null"), *_TRACKING_BASE_COLUMNS, *extra, *_PERFORMANCE_COLUMNS)
            + (_CREATED_AT, _UPDATED_AT)
        ),
        access=SHARED_READ,
        constraints=(f"constraint {name}_code_date_key unique (code, recommend_date)",),
        indexes=(f"create index if not exists {name}_date_idx on public.{name} (recommend_date desc, code)",),
    )


_CN_TRACKING_EXTRA: tuple[Column, ...] = (
    ("recommend_count", "integer not null default 1"),
    ("step3_verdict", "text"),
    *_RECOMMENDATION_ATTRIBUTION_COLUMNS,
    *_candidate_attribution_columns(),
    *_versioned(recommendation_tracking_schema.MISSING_COLUMNS),
)

_SPRINGBOARD_OBSERVATION_COLUMNS: tuple[Column, ...] = (
    ("springboard_grade", "text"),
    ("springboard_met_count", "integer"),
    ("springboard_a", "boolean"),
    ("springboard_b", "boolean"),
    ("springboard_c", "boolean"),
    ("springboard_support", "numeric"),
    ("springboard_touch_count", "integer"),
    ("springboard_evidence", "jsonb"),
)

TABLES: tuple[TableSpec, ...] = (
    TableSpec(
        name=TABLE_PLANET_MEMBERS,
        columns=(
            ("user_id", "text primary key"),
            _CREATED_AT,
            ("expires_on", "date"),
        ),
        access=OWN_USER_READ,
        comment="星球会员事实表，见 docs/PLANET_MEMBERSHIP.md。MEMBERSHIP_MODE=off 时不再查询。",
    ),
    TableSpec(
        name=TABLE_USER_SETTINGS,
        columns=(
            ("user_id", "text primary key"),
            ("chat_provider", "text"),
            *(
                (f"{provider}_{field}", "text")
                for provider in ("gemini", "openai", "deepseek", "anthropic")
                for field in ("api_key", "model", "base_url")
            ),
            ("custom_providers", "jsonb not null default '{}'::jsonb"),
            ("tickflow_api_key", "text"),
            ("tushare_token", "text"),
            ("feishu_webhook", "text"),
            ("wecom_webhook", "text"),
            ("dingtalk_webhook", "text"),
            ("tg_bot_token", "text"),
            ("tg_chat_id", "text"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=OWN_USER_ALL,
    ),
    TableSpec(
        name=TABLE_ANALYTICS_EXCLUDED_USERS,
        columns=(("user_id", "text primary key"), ("note", "text"), _CREATED_AT),
        access=OWN_USER_READ,
    ),
    TableSpec(
        name=TABLE_USER_ACTIVITY_EVENTS,
        columns=(
            ("event_id", "text primary key"),
            ("user_id", "text not null"),
            ("source", "text not null default 'web'"),
            ("session_id", "text"),
            ("event_name", "text not null default 'page_view'"),
            ("feature", "text"),
            ("route", "text"),
            ("success", "boolean not null default true"),
            ("duration_ms", "integer"),
            ("app_version", "text"),
            ("metadata", "jsonb not null default '{}'::jsonb"),
            ("client_ts", "timestamptz"),
            _CREATED_AT,
        ),
        access=ACTIVITY_EVENTS,
        indexes=(
            f"create index if not exists {TABLE_USER_ACTIVITY_EVENTS}_user_idx "
            f"on public.{TABLE_USER_ACTIVITY_EVENTS} (user_id, created_at desc)",
        ),
    ),
    TableSpec(
        name=TABLE_USER_DAILY_ACTIVITY,
        columns=(
            ("activity_date", "date not null"),
            ("user_id", "text not null"),
            ("sources", "jsonb not null default '[]'::jsonb"),
            ("event_count", "integer not null default 0"),
            ("session_count", "integer not null default 0"),
            ("first_seen_at", "timestamptz"),
            ("last_seen_at", "timestamptz"),
            ("feature_counts", "jsonb not null default '{}'::jsonb"),
            _UPDATED_AT,
        ),
        access=ACTIVITY_DAILY,
        constraints=(f"constraint {TABLE_USER_DAILY_ACTIVITY}_pkey primary key (activity_date, user_id)",),
    ),
    TableSpec(
        name=TABLE_PORTFOLIOS,
        columns=(
            ("portfolio_id", "text primary key"),
            ("name", "text not null default ''"),
            ("free_cash", "numeric not null default 0"),
            ("total_equity", "numeric"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=PORTFOLIO_ALL,
        comment="portfolio_id 形如 USER_LIVE:<auth.uid()>，RLS 按冒号后的用户 ID 隔离。",
    ),
    TableSpec(
        name=TABLE_PORTFOLIO_POSITIONS,
        columns=(
            ("portfolio_id", "text not null"),
            ("code", "text not null"),
            ("name", "text not null default ''"),
            ("shares", "integer not null default 0"),
            ("cost_price", "numeric not null default 0"),
            ("buy_dt", "text not null default ''"),
            ("stop_loss", "numeric"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=PORTFOLIO_ALL,
        constraints=(f"constraint {TABLE_PORTFOLIO_POSITIONS}_pkey primary key (portfolio_id, code)",),
        comment="buy_dt 历史上混用 YYYYMMDD 与空串，保持 text，由写入边界归一化。",
    ),
    TableSpec(
        name=TABLE_TRADE_ORDERS,
        columns=(
            _ID,
            ("run_id", "text not null"),
            ("portfolio_id", "text not null"),
            ("trade_date", "date not null"),
            ("model", "text"),
            ("market_view", "text not null default ''"),
            ("code", "text not null"),
            ("name", "text not null default ''"),
            ("action", "text not null"),
            ("status", "text not null"),
            ("shares", "integer not null default 0"),
            ("price_hint", "numeric"),
            ("amount", "numeric not null default 0"),
            ("stop_loss", "numeric"),
            ("max_loss", "numeric not null default 0"),
            ("drawdown_ratio", "numeric not null default 0"),
            ("reason", "text not null default ''"),
            ("tape_condition", "text not null default ''"),
            ("invalidate_condition", "text not null default ''"),
            _CREATED_AT,
        ),
        access=PORTFOLIO_READ,
        indexes=(
            f"create index if not exists {TABLE_TRADE_ORDERS}_portfolio_date_idx "
            f"on public.{TABLE_TRADE_ORDERS} (portfolio_id, trade_date desc)",
        ),
        comment="AI 建议单，不是成交流水；状态只有 APPROVED / NO_TRADE / CANCELLED。",
    ),
    TableSpec(
        name=TABLE_DAILY_NAV,
        columns=(
            ("portfolio_id", "text not null"),
            ("trade_date", "date not null"),
            ("free_cash", "numeric not null default 0"),
            ("positions_value", "numeric not null default 0"),
            ("total_equity", "numeric not null default 0"),
            *_versioned(daily_nav_schema.DAY_PNL_COLUMNS),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=PORTFOLIO_READ,
        constraints=(f"constraint {TABLE_DAILY_NAV}_pkey primary key (portfolio_id, trade_date)",),
    ),
    _tracking_table(TABLE_RECOMMENDATION_TRACKING, "integer", _CN_TRACKING_EXTRA),
    _tracking_table(TABLE_RECOMMENDATION_TRACKING_HK, "text"),
    _tracking_table(TABLE_RECOMMENDATION_TRACKING_US, "text"),
    TableSpec(
        name=TABLE_SIGNAL_PENDING,
        columns=_dedupe(
            (
                _ID,
                ("code", "integer not null"),
                ("name", "text not null default ''"),
                ("signal_type", "text not null"),
                ("signal_date", "date not null"),
                ("status", "text not null default 'pending'"),
                ("signal_score", "numeric not null default 0"),
                ("ttl_days", "integer"),
                ("days_elapsed", "integer not null default 0"),
                ("regime", "text not null default ''"),
                ("industry", "text not null default ''"),
                *(
                    (f"snap_{field}", "numeric")
                    for field in ("open", "high", "low", "close", "volume", "support", "ma20", "ma50")
                ),
                ("confirm_reason", "text not null default ''"),
                ("confirm_date", "date"),
                ("expire_date", "date"),
                *_candidate_attribution_columns(),
                _CREATED_AT,
                _UPDATED_AT,
            )
        ),
        access=SHARED_READ,
        indexes=(
            # 与 integrations/supabase_signal_pending.py 的去重语义一致：只有活跃态占用唯一键。
            f"create unique index if not exists uq_signal_pending_active on public.{TABLE_SIGNAL_PENDING} "
            "(code, signal_type) where status in ('pending', 'survived')",
            f"create index if not exists {TABLE_SIGNAL_PENDING}_date_idx "
            f"on public.{TABLE_SIGNAL_PENDING} (signal_date desc)",
        ),
    ),
    TableSpec(
        name=TABLE_MARKET_SIGNAL_DAILY,
        columns=(
            ("trade_date", "date primary key"),
            ("benchmark_regime", "text"),
            ("main_index_code", "text"),
            ("main_index_close", "numeric"),
            ("main_index_ma50", "numeric"),
            ("main_index_ma200", "numeric"),
            ("main_index_recent3_cum_pct", "numeric"),
            ("main_index_today_pct", "numeric"),
            ("smallcap_index_code", "text"),
            ("smallcap_close", "numeric"),
            ("smallcap_recent3_cum_pct", "numeric"),
            ("a50_value_date", "date"),
            ("a50_source", "text"),
            ("a50_close", "numeric"),
            ("a50_pct_chg", "numeric"),
            ("vix_value_date", "date"),
            ("vix_source", "text"),
            ("vix_close", "numeric"),
            ("vix_pct_chg", "numeric"),
            ("premarket_regime", "text"),
            ("premarket_reasons", "jsonb not null default '[]'::jsonb"),
            ("benchmark_slot", "text"),
            ("premarket_slot", "text"),
            ("market_posture_code", "text"),
            ("market_posture_name", "text"),
            ("wind_phrase", "text"),
            ("water_phrase", "text"),
            ("action_phrase", "text"),
            ("banner_title", "text"),
            ("banner_message", "text"),
            ("banner_tone", "text"),
            ("source_jobs", "jsonb not null default '{}'::jsonb"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
    ),
    TableSpec(
        name=TABLE_CONCEPT_HEAT_HISTORY,
        columns=(
            _ID,
            ("trade_date", "date not null"),
            ("concept_name", "text not null"),
            ("pct", "numeric not null default 0"),
            ("net_inflow", "numeric not null default 0"),
            ("rank", "integer"),
            ("source_id", "text not null default ''"),
            _CREATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_CONCEPT_HEAT_HISTORY}_key unique (trade_date, concept_name)",),
    ),
    TableSpec(
        name=TABLE_THEME_RADAR_SNAPSHOT,
        columns=(
            ("trade_date", "date primary key"),
            ("snapshot_json", "jsonb not null"),
            ("top_themes", "jsonb not null default '[]'::jsonb"),
            ("top_candidates", "jsonb not null default '[]'::jsonb"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
    ),
    TableSpec(
        name=TABLE_EXTERNAL_SEED_OBSERVATIONS,
        columns=(
            _ID,
            ("market", "text not null"),
            ("trade_date", "date not null"),
            ("source", "text not null"),
            ("code", "text not null"),
            ("name", "text not null default ''"),
            ("industry", "text not null default ''"),
            ("source_rank", "integer"),
            ("passed_l1", "boolean not null default false"),
            ("passed_l2", "boolean not null default false"),
            ("l4_confirmed", "boolean not null default false"),
            ("l4_trigger_tags", "jsonb not null default '[]'::jsonb"),
            ("watch_status", "text"),
            ("watch_ttl_days", "integer"),
            ("expires_at", "date"),
            ("allow_l2_bypass_review", "boolean not null default false"),
            ("raw_payload", "jsonb not null default '{}'::jsonb"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_EXTERNAL_SEED_OBSERVATIONS}_key unique (market, trade_date, source, code)",),
    ),
    TableSpec(
        name=TABLE_SIGNAL_OBSERVATIONS,
        columns=(
            _ID,
            ("market", "text not null default 'cn'"),
            ("trade_date", "date not null"),
            ("code", "text not null"),
            ("name", "text not null default ''"),
            ("signal_type", "text not null"),
            ("track", "text"),
            ("regime", "text not null default 'NEUTRAL'"),
            ("industry", "text not null default ''"),
            ("stage", "text not null default ''"),
            ("channel", "text not null default ''"),
            ("profile_tag", "text"),
            ("stage_tag", "text"),
            ("trigger_tags", "jsonb not null default '[]'::jsonb"),
            ("selection_mode", "text"),
            ("policy_version", "text"),
            ("candidate_rank", "integer"),
            ("trigger_score", "numeric"),
            ("priority_score", "numeric"),
            ("entry_price", "numeric not null default 0"),
            ("selected_for_ai", "boolean not null default false"),
            ("ai_recommended", "boolean not null default false"),
            ("source", "text not null default 'funnel'"),
            ("strategy_version", "text"),
            ("candidate_lane", "text"),
            ("entry_type", "text"),
            ("signal_key", "text"),
            ("candidate_status", "text"),
            ("lifecycle_status", "text not null default 'ACTIVE'"),
            ("features_json", "jsonb not null default '{}'::jsonb"),
            *_SPRINGBOARD_OBSERVATION_COLUMNS,
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_SIGNAL_OBSERVATIONS}_key unique (market, trade_date, code, signal_type)",),
        indexes=(
            f"create index if not exists {TABLE_SIGNAL_OBSERVATIONS}_market_date_idx "
            f"on public.{TABLE_SIGNAL_OBSERVATIONS} (market, trade_date desc, id desc)",
        ),
    ),
    TableSpec(
        name=TABLE_SIGNAL_OUTCOMES,
        columns=(
            _ID,
            ("observation_id", "bigint not null"),
            ("market", "text not null default 'cn'"),
            ("trade_date", "date not null"),
            ("code", "text not null"),
            ("signal_type", "text not null"),
            ("track", "text"),
            ("regime", "text not null default 'NEUTRAL'"),
            ("horizon_days", "integer not null"),
            ("status", "text not null"),
            ("return_pct", "numeric"),
            ("max_drawdown_pct", "numeric"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_SIGNAL_OUTCOMES}_key unique (observation_id, horizon_days)",),
        indexes=(
            f"create index if not exists {TABLE_SIGNAL_OUTCOMES}_market_status_idx "
            f"on public.{TABLE_SIGNAL_OUTCOMES} (market, status, id desc)",
            f"create index if not exists {TABLE_SIGNAL_OUTCOMES}_market_date_idx "
            f"on public.{TABLE_SIGNAL_OUTCOMES} (market, trade_date desc, id desc)",
        ),
        comment="observation_id 不设外键：回填会删旧观察重插，外键会级联删掉已算好的结果。",
    ),
    TableSpec(
        name=TABLE_SIGNAL_HEALTH_DAILY,
        columns=(
            _ID,
            ("market", "text not null"),
            ("as_of_date", "date not null"),
            ("signal_type", "text not null"),
            ("track", "text"),
            ("regime", "text not null"),
            ("horizon_days", "integer not null"),
            ("sample_count", "integer not null default 0"),
            ("win_rate_pct", "numeric"),
            ("avg_return_pct", "numeric"),
            ("median_return_pct", "numeric"),
            ("avg_drawdown_pct", "numeric"),
            ("health_state", "text"),
            ("weight_multiplier", "numeric"),
            ("reason", "text not null default ''"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(
            f"constraint {TABLE_SIGNAL_HEALTH_DAILY}_key "
            "unique (market, as_of_date, signal_type, regime, horizon_days)",
        ),
    ),
    TableSpec(
        name=TABLE_SIGNAL_REGISTRY,
        columns=(
            _ID,
            ("market", "text not null"),
            ("signal_type", "text not null"),
            ("track", "text"),
            ("regime", "text not null"),
            ("status", "text not null default 'ACTIVE'"),
            ("weight_multiplier", "numeric not null default 1"),
            ("sample_count", "integer not null default 0"),
            ("win_rate_pct", "numeric"),
            ("avg_return_pct", "numeric"),
            ("horizon_days", "integer"),
            ("reason", "text not null default ''"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_SIGNAL_REGISTRY}_key unique (market, signal_type, regime)",),
    ),
    TableSpec(
        name=TABLE_SIGNAL_POLICY_SHADOW_RUNS,
        columns=(
            _ID,
            ("market", "text not null"),
            ("trade_date", "date not null"),
            ("regime", "text"),
            ("schema_version", "text"),
            ("snapshot_level", "text"),
            ("base_policy", "jsonb"),
            ("shadow_policy", "jsonb"),
            ("signal_weights", "jsonb"),
            *_versioned(signal_policy_shadow_schema.MISSING_COLUMNS),
            *(
                (name, "jsonb not null default '[]'::jsonb")
                for name in ("base_selected", "shadow_selected", "diff_added", "diff_removed")
            ),
            *(
                (name, "jsonb")
                for name in ("selection_summary", "policy_summary", "registry_summary", "health_summary")
            ),
            ("registry_snapshot", "jsonb not null default '[]'::jsonb"),
            ("health_snapshot", "jsonb not null default '[]'::jsonb"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_SIGNAL_POLICY_SHADOW_RUNS}_key unique (market, trade_date)",),
    ),
    TableSpec(
        name=TABLE_STRATEGY_ATTRIBUTION_REPORTS,
        columns=(
            _ID,
            ("report_date", "date not null"),
            ("market", "text not null"),
            ("window_start", "date not null"),
            ("window_end", "date not null"),
            ("horizons", "jsonb not null default '[]'::jsonb"),
            *(
                (name, "jsonb")
                for name in (
                    "summary_json",
                    "signal_stats_json",
                    "signal_context_stats_json",
                    "score_bucket_stats_json",
                    "shadow_diff_stats_json",
                    "top_winners_json",
                    "top_losers_json",
                    "recommendations_json",
                )
            ),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(
            f"constraint {TABLE_STRATEGY_ATTRIBUTION_REPORTS}_key unique (report_date, market, window_start, window_end)",
        ),
        comment="单行可达数百 KB，db_maintenance 只保留 30 天。",
    ),
    TableSpec(
        name=TABLE_STRATEGY_REFLECTIONS,
        columns=(
            _ID,
            ("market", "text not null"),
            ("as_of_date", "date not null"),
            ("horizon_days", "integer not null"),
            ("status", "text not null default 'SHADOW'"),
            ("summary", "jsonb not null default '{}'::jsonb"),
            ("reflection_text", "text not null default ''"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_STRATEGY_REFLECTIONS}_key unique (market, as_of_date, horizon_days)",),
    ),
    TableSpec(
        name=TABLE_STRATEGY_POLICY_CANDIDATES,
        columns=(
            _ID,
            ("market", "text not null"),
            ("as_of_date", "date not null"),
            ("status", "text not null"),
            ("source_reflection_date", "date"),
            ("candidate_policy", "jsonb not null default '{}'::jsonb"),
            ("validation_summary", "jsonb not null default '{}'::jsonb"),
            _CREATED_AT,
            _UPDATED_AT,
        ),
        access=SHARED_READ,
        constraints=(f"constraint {TABLE_STRATEGY_POLICY_CANDIDATES}_key unique (market, as_of_date)",),
    ),
)

# 建表语句由已有模块提供的表（本模块只负责 RLS 与策略）。
VERSIONED_TABLES: tuple[tuple[str, str], ...] = (
    (TABLE_FACTOR_IC_DAILY, SHARED_READ),
    (TABLE_REVIEW_CAPTURE_DAILY, SHARED_READ),
    (TABLE_REVIEW_SHADOW_LANE_DAILY, SHARED_READ),
    *((name, SERVICE_ONLY) for name in shadow_ledger_schema.table_names()),
)

_UID = "(select auth.uid())::text"
_PORTFOLIO_OWNER = f"split_part(portfolio_id, ':', 2) = {_UID}"


def table_access() -> dict[str, str]:
    """全部表名 → 访问模式。"""
    return {**{spec.name: spec.access for spec in TABLES}, **dict(VERSIONED_TABLES)}


def _create_table(spec: TableSpec) -> str:
    parts = [f"  {name} {ddl}" for name, ddl in spec.columns] + [f"  {c}" for c in spec.constraints]
    lines = [f"create table if not exists public.{spec.name} (", ",\n".join(parts), ");"]
    lines.extend(f"{index};" for index in spec.indexes)
    if spec.comment:
        comment = spec.comment.replace("'", "''")
        lines.append(f"comment on table public.{spec.name} is '{comment}';")
    return "\n".join(lines)


def _policy(table: str, suffix: str, command: str, *, using: str | None = None, check: str | None = None) -> str:
    name = f"{table}_{suffix}"
    clauses = [f"create policy {name} on public.{table} for {command} to authenticated"]
    if using:
        clauses.append(f"  using ({using})")
    if check:
        clauses.append(f"  with check ({check})")
    return f"drop policy if exists {name} on public.{table};\n" + "\n".join(clauses) + ";"


def _policy_statements(table: str, access: str) -> list[str]:
    own = f"user_id = {_UID}"
    if access == OWN_USER_READ:
        return [_policy(table, "select_own", "select", using=own)]
    if access == OWN_USER_ALL:
        return [_policy(table, "all_own", "all", using=own, check=own)]
    if access == ACTIVITY_EVENTS:
        return [
            _policy(table, "select_own", "select", using=own),
            _policy(table, "insert_own", "insert", check=own),
        ]
    if access == ACTIVITY_DAILY:
        return [
            _policy(table, "select_own", "select", using=own),
            _policy(table, "insert_own", "insert", check=own),
            _policy(table, "update_own", "update", using=own, check=own),
        ]
    if access == PORTFOLIO_ALL:
        return [_policy(table, "all_own", "all", using=_PORTFOLIO_OWNER, check=_PORTFOLIO_OWNER)]
    if access == PORTFOLIO_READ:
        return [_policy(table, "select_own", "select", using=_PORTFOLIO_OWNER)]
    if access == SHARED_READ:
        return [_policy(table, "select_authenticated", "select", using="true")]
    if access == SERVICE_ONLY:
        return []
    raise ValueError(f"unknown access mode {access!r} for {table}")


def _rls_block(access_map: dict[str, str]) -> str:
    lines = [
        "-- RLS：未列出的角色与操作一律拒绝；service_role 绕过 RLS，供定时任务写库。",
    ]
    for table, access in access_map.items():
        lines.append(f"alter table public.{table} enable row level security;")
        lines.append(f"revoke all on table public.{table} from anon;")
        lines.extend(_policy_statements(table, access))
    return "\n".join(lines)


def build_ddl() -> str:
    """生成完整、幂等的建库脚本。

    重复执行只会补建缺失的表、索引与策略；已存在的表不会补列，上游新增列时要另写
    ``alter table ... add column if not exists``（参照 core/*_schema.py 的补列模块）。
    """
    blocks = [
        "-- WyckoffTradingAgent 自部署完整 schema。由 core/self_host_schema.py 生成，请勿手改。",
        "-- 在 Supabase SQL Editor 中整段执行；脚本幂等，可重复执行。",
        "begin;",
        *(_create_table(spec) for spec in TABLES),
        "-- 以下建表语句来自已有的 schema 模块。",
        factor_ic_schema.build_ddl(),
        review_capture_schema.build_ddl(),
        review_shadow_lane_schema.build_ddl(),
        shadow_ledger_schema.build_ddl(),
        _rls_block(table_access()),
        "notify pgrst, 'reload schema';",
        "commit;",
    ]
    return "\n\n".join(block.strip() for block in blocks) + "\n"
